language: node_js
node_js:
- 5.6.0
sudo: false
deploy:
  provider: npm
  email: jarrett@thestyl.us
  api_key:
    secure: D62lqzIRXkU54W1Osh4ss6CnKZ/F0LfCsXPr7bBBCKyz1Vzb2/WIIoOvk+3GX5QxxOaf8YTExpN3pggBfBW5uNPAni+9se5O1wRFFkbkZAuyvndmgf2VOd3QRSYLiTXHB398MOMvZYxG1HiNBDg+GeXAzTwK9lTfUWxhCQHQbOw=
  on:
    tags: true
    repo: kuatsure/helpful-helpers
notifications:
  email: false
  slack:
    secure: TnTdCaNI7WXyZf7lklMPzY3xNx6Eg2DlVzPyZG3IKUhAKufwkPb1nkONYmkH2JTi08KptTXvkjlUi9StDkj9lmbmEAWRJ1pez0l2YJpB29035ia7C/UODK6I33Rvqi8ghj6FjXrnp9L794DwWQHwyMylFwp9diUPLciHclERgjE=
